Update to nim 2 x
codex-storage/nim-datastore pull request #75
Opened 2024-12-13 08:48 UTC by 2-towns

This PR contains the changes to move to Nim 2.0. It includes dependency updates and one fix for trying to set nil to a distinct pointer, which is no longer supported by Nim 2.0:

https://github.com/codex-storage/nim-datastore/commit/7e053e5e0d2b783ece0e850a750012f1eac3ed69

2025-02-11 11:32 UTC, benbierens submitted a review, later dismissed

2025-02-12 23:56 UTC, emizzle requested changes

2025-02-12 23:56 UTC, emizzle commented on datastore.nimble
> +         "sqlite3_abi == 3.47.0.0",
Do other minor versions break the build? eg
```suggestion
         "sqlite3_abi >= 3.47.0.0 & < 4.0.0.0",
```

2025-02-12 23:56 UTC, emizzle commented on datastore.nimble
> +         "leveldbstatic >= 0.2.0 & < 1.0.0",
I think a lot of nim libs use the second digit as a major version indicator 🤷 It should not be the case imo.
```suggestion
         "leveldbstatic >= 0.2.0 & < 0.3.0",
```

2025-02-12 23:56 UTC, emizzle commented on datastore.nimble
> +         "unittest2 >= 0.2.3"
```suggestion
         "stew >= 0.2.0 & < 0.3.0",
         "unittest2 >= 0.2.3 & < 0.3.0"
```

2025-02-13 04:56 UTC, emizzle approved these changes

2025-02-13 15:50 UTC, benbierens approved these changes

2025-02-13 19:26 UTC, merged